name = "LinkedLists"
uuid = "1cab1b77-73a4-4223-8626-edcdbc6e6265"
authors = ["Kristof Cools <krcools@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
